#!/usr/bin/with-contenv bash

if which node > /dev/null
then
    echo "**** node is installed, skipping... ****"
else
    echo "**** install runtime packages ****"
    echo "**** apt-get update ****"
    apt-get update
    echo "**** install binutils, libatomic1, file, unzip ****"
    apt-get install -y binutils libatomic1 file unzip
    echo "**** install Intel Drivers ****"
    apt-get install -y intel-media-va-driver-non-free libigdgmm-dev vainfo
    echo "**** install 'n' ****"
    curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
    echo "**** install nodejs ****"
    bash n lts
fi

