version: '3.8'

services:
  server:
    image: ghcr.io/felixclements/clusterplex_pms:master
    environment:
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      ORCHESTRATOR_URL: http://orchestrator:3500
      PMS_SERVICE: server # This service. If you disable Local Relay then you must use PMS_IP instead
      PMS_PORT: "32400"
      TRANSCODE_OPERATING_MODE: remote #(local|remote|both)
      TRANSCODER_VERBOSE: "1"   # 1=verbose, 0=silent
      LOCAL_RELAY_ENABLED: "1"
      LOCAL_RELAY_PORT: "32499"
      FFMPEG_HWACCEL: vaapi
      LIBVA_DRIVER_NAME: iHD
    healthcheck:
      test: curl -fsS http://localhost:32400/identity > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    volumes:
      - /opt/plex_server/config:/config
      - /mnt/media/TV:/data/tv
      - /mnt/media/Music:/data/music
      - /mnt/media/Films:/data/movies
      - /mnt/glusterfs/plex_server/transcode:/transcode
      - /mnt/glusterfs/plex_server/Drivers:/config/Library/Application Support/Plex Media Server/Drivers
      - /mnt/glusterfs/plex_server/Cache:/config/Library/Application Support/Plex Media Server/Cache
      - /dev/dri/:/dev/dri/
    devices:
      - /dev/dri:/dev/dri
    networks:
      - network_public
    ports:
      - 32499:32499     # LOCAL_RELAY_PORT
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

  orchestrator:
    image: ghcr.io/felixclements/clusterplex_orchestrator:master
      update_config:
        order: start-first
    healthcheck:
      test: curl -fsS http://localhost:3500/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    environment:
      TZ: Europe/London
      LISTENING_PORT: 3500
      WORKER_SELECTION_STRATEGY: "LOAD_TASKS" # RR | LOAD_CPU | LOAD_TASKS | LOAD_RANK (default)
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - network_public
    ports:
      - 3500:3500

  worker:
    image: ghcr.io/felixclements/clusterplex_worker:master
    hostname: "plex-worker-{{.Node.Hostname}}"
    deploy:
      mode: global
    environment:
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      LISTENING_PORT: 3501      # used by the healthcheck
      STAT_CPU_INTERVAL: 2000   # interval for reporting worker load metrics
      ORCHESTRATOR_URL: http://orchestrator:3500
      EAE_SUPPORT: "1"
      FFMPEG_HWACCEL: vaapi
      LIBVA_DRIVER_NAME: iHD
      #LIBVA_DRIVERS_PATH: /usr/lib/x86_64-linux-gnu/dri
    healthcheck:
      test: curl -fsS http://localhost:3501/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 240s
    volumes:
      - /opt/plex_worker/codecs:/codecs # (optional)
      - /mnt/media/TV:/data/tv
      - /mnt/media/Films:/data/movies
      - /mnt/media/Music:/data/music
      - /mnt/glusterfs/plex_server/transcode:/transcode
      - /mnt/glusterfs/plex_server/Drivers:/config/Library/Application Support/Plex Media Server/Drivers
      - /mnt/glusterfs/plex_server/Cache:/config/Library/Application Support/Plex Media Server/Cache
      - /dev/dri/:/dev/dri/
    devices:
      - /dev/dri:/dev/dri
    networks:
      - network_public

networks:
  network_public:
    external: true
