version: "3.8"

services:
  dmm:
    image: docker
    deploy:
      mode: global
    entrypoint: docker
    command: |
      run
      -i
      --name device-manager
      --restart always
      --privileged
      --cgroupns=host
      --pid=host
      --userns=host
      -v /sys:/host/sys
      -v /var/run/docker.sock:/var/run/docker.sock
      ghcr.io/allfro/allfro/device-mapping-manager:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
