version: "3.2"

# What is this?
#
# This stack exists solely to deploy the swarm public overlay network, so that other stack can attach to it.

services:
  scratch:
    image: scratch
    deploy:
      replicas: 0
    networks:
      - public

networks:
  public:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.16.200.0/24
