name: Sync with Upstream Repository

on:
  schedule:
    - cron: '0 0 * * *' # Scheduled for midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. Use the latest checkout action (v4)
      - name: Checkout the Repository
        uses: actions/checkout@v4
        with:
          ref: master # Changed to 'master' as per your setup

      # 2. Set up Git user details
      - name: Set up Git
        run: |
          git config --global user.name 'FelixClements'
          git config --global user.email 'mvr600@gmail.com'

      # 3. Add the upstream remote (where you want to pull changes from)
      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/pabloromeo/clusterplex.git

      # 4. Fetch upstream changes
      - name: Fetch Upstream Changes
        run: git fetch upstream --verbose

      # 5. Attempt to merge upstream/master
      - name: Merge Upstream Changes
        run: |
          echo "Checking out the local master branch..."
          if ! git checkout master; then
            echo "Error: Failed to checkout master branch." >&2
            exit 1
          fi

          echo "Merging changes from upstream/master while allowing unrelated histories..."
          if ! git merge upstream/master --no-edit --allow-unrelated-histories; then
            echo "Merge conflict or error detected during the merge. Aborting." >&2
            git merge --abort || echo "No merge to abort."
            exit 1
          fi

      # 6. Push back to your fork only if the merge succeeds
      - name: Push Changes to Fork
        if: success()
        run: git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
