name: Sync Specific Sub-Folders from Upstream Repository

on:
  schedule:
    - cron: '0 0 * * *' # Scheduled for midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your own master branch
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: master

      # 2. Setup git user details
      - name: Set up Git
        run: |
          git config --global user.name 'FelixClements'
          git config --global user.email 'mvr600@gmail.com'

      # 3. Initialize sparse-checkout and add the upstream fork
      - name: Enable Sparse Checkout for specific sub-folders
        run: |
          # Add upstream repo
          git remote add upstream https://github.com/pabloromeo/clusterplex.git
          git fetch upstream

          # Initialize sparse-checkout
          git sparse-checkout init

          # Add sub-folders (adjust paths to your needs)
          git sparse-checkout set orchestrator pms/app worker/app

          echo "Sparse checkout setup complete. Syncing selected sub-directories only!"

      # 4. Merge upstream changes for selected sub-folders only
      - name: Merging changes from upstream/master for selected folders
        run: |
          # Ensure we're on your local master branch
          git checkout master

          # Merge changes from upstream/master
          git merge upstream/master --no-edit --allow-unrelated-histories

      # 5. Push changes if merge was successful
      - name: Push changes to your fork
        if: success()
        run: git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
